name=CoolNeon DevShield
version=1.1.0
author=Chris Knight
maintainer=https://github.com/ghstwhl
sentence=Arduino library for the CoolNeon Arduino Developer Shield.
paragraph=Provides pin definitions and setup for the CoolNeon Arduino Developer Shield inputs: four potentiometers, two momentary buttons, and two two-position switches.
category=Other
url=https://github.com/CoolNeon/CoolNeon_devshield/
architectures=*
includes=DevShield.h
